website/music/urls.py
from django.conf.urls import url
from . import views

# . means current file
app_name="music"
urlpatterns = [
    #/music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/music/123 or album id/(lecture 12 tnb for this r.e.) #for url pattern
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #/music/123 or album id/favorite /(lecture 22)
    #url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name="favorite "),
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

website/music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo =  models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + " - " + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/music/views.py
'''from django.shortcuts import render, get_object_or_404
from .models import Album, Song

def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums': all_albums}
    return render(request, 'music/index.html', context)

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "You Did Not Select A Valid Song.",
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})'''

from django.views import generic
from .models import Album

class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return  Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/index.html'

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MusicServer{% endblock %}</title>
     {% load staticfiles %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" />
 <link rel="stylesheet" href="{% static 'music/style.css' %}" />
 <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>

<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar" >
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">MusicServer</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" sria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-music" sria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                 <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log out
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Albums{% endblock %}
{% block body %}
<img src = "{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:detail' album.id %}"  method="POST">
    {% csrf_token %}
    {% for song in album.song_set.all %}
         <input type="radio" id="song{{ forloop.counter }}"  name="song" value="{{ song.id }}"/>
         <label for="song{{ forloop.counter }}">
             {{  song.song_title }}
             {% if song.is_favorite %}
                 <strong>Fav</strong>
             {% endif %}
         </label><br>
    {% endfor %}
    <input type="submit"  value="Favorite" >
</form>
{% endblock %}

website/music/templates/music/index.html
 <!-- Loads the path to your static files -->
{% extends 'music/base.html' %}
 {% block body %}
        {% if all_albums %}
         <h3 xmlns:music="http://www.w3.org/1999/xhtml"> Here are all of our Albums</h3>
            <ul>
                {% for album in all_albums %}
                    <li><a href="{% url 'music:detail' album.id %}" >{{ album.album_title }}</a></li>
                {% endfor %}
            </ul>
         {% else %}
             <h3> No album available</h3>
         {% endif %}
{% endblock %}